name: build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: vtavernier
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute Docker image tag
        run: |
          echo "::set-output name=tag::$(awk -F'[ =]' '/^ARG MONERO_VERSION/ {print $NF}' Dockerfile)"
          echo "::set-output name=repository::ghcr.io/vtavernier/monero"
        id: image

      - name: Build and export Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.image.outputs.repository }}:${{ steps.image.outputs.tag }}

      - name: Test Docker image
        run: |
          docker run --rm ${{ steps.image.outputs.repository }}:${{ steps.image.outputs.tag }} start-monerod.sh --version

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.image.outputs.repository }}:${{ steps.image.outputs.tag }}
            ${{ steps.image.outputs.repository }}:latest
