name: update

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 12 15 * *"

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      current_release: ${{ steps.update.outputs.current_release }}
      latest_release: ${{ steps.update.outputs.latest_release }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for updates
        run: |
          LATEST_RELEASE=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/monero-project/monero/releases | jq -r '.[0].tag_name' | cut -dv -f2)
          CURRENT_RELEASE=$(awk -F'[ =]' '/^ARG MONERO_VERSION/ {print $NF}' Dockerfile)

          echo "::set-output name=latest_release::$LATEST_RELEASE"
          echo "::set-output name=current_release::$CURRENT_RELEASE"
        id: update

  build:
    runs-on: ubuntu-latest

    needs: check
    if: needs.check.outputs.current_release != needs.check.outputs.latest_release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Prepare update commit
        run: |
          git config --global user.name 'Vincent Tavernier'
          git config --global user.email 'vtavernier@users.noreply.github.com'
          sed -i 's/=${{ needs.check.outputs.current_release }}/=${{ needs.check.outputs.latest_release }}/' Dockerfile
          git commit -m 'Update monero to ${{ needs.check.outputs.latest_release }}' Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Compute Docker image tag
        run: |
          echo "::set-output name=tag::${{ needs.check.outputs.latest_release }}"
          echo "::set-output name=repository::ghcr.io/vtavernier/monero"
        id: image

      - name: Build and export Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.image.outputs.repository }}:${{ steps.image.outputs.tag }}

      - name: Test Docker image
        run: |
          docker run --rm ${{ steps.image.outputs.repository }}:${{ steps.image.outputs.tag }} start-monerod.sh --version

      - name: Push update commit
        run: |
          git push
